host compiler needs to be 32 bit (-m32)
Because of v8:
deps/v8/src/base/build_config.h:156:2: error: #error Target architecture arm is only supported on arm and ia32 host